### ISSUE TITLE
methods have invalid signatures

### ISSUE THREAD

**Issue by ntessore** [ntessore/positional_defaults#1]
The default `Signature.replace()` breaks with the left-defaults, so it's currently impossible to obtain signatures from methods:

```py
from leftdefault import leftdefault
from inspect import signature

class A:
    @leftdefault(skip=1)
    def interval(self, stop, start=0, /, step=1):
        return (start, stop, step)

print(signature(A().interval))
# ValueError: non-default argument follows default argument
```

**Comment by nstarman** [comment]
`inspect` uses a sentinel `Missing` for arguments without defaults. Could that be hacked by providing a custom sentinel? `LeftDefaultSignature` would know about the new sentinel, but the standard `Signature` would not, think it's a real default, and not complain.
