### ISSUE TITLE
mypyc compilation

### ISSUE THREAD

**Issue by nstarman** [ntessore/positional_defaults#6]
The testing of which requires cibuildwheels.

**Comment by ntessore** [comment]
With the new package, this already works great and brings performance roughly in line with a plain `*args, **kwargs` decorator:


```console
$ # need to remove pyproject.toml for mypyc not to break, investigate
$ mv pyproject.tom{l,_} && mypyc positional_defaults.py && mv pyproject.tom{_,l}
$ python test_performance.py
```

**Comment by ntessore** [comment]
For distribution, I believe this can have both compiled wheels from `cibuildwheel` and a `none-any.whl` for everywhere else.

**Comment by nstarman** [comment]
Yes. I have a setup that has both distribution types... https://github.com/nstarman/overload_numpy

**Comment by nstarman** [comment]
The pyproject.toml works there. Not sure what's different abbot the setup. Maybe `src` ?

**Comment by ntessore** [comment]
It was a plain `mypyc positional_defaults.py` that broke, outside of setuptools. Maybe it couldn't figure out the package module without a src folder, as you say.

**Comment by ntessore** [comment]
The environment variable is a good idea for cibuildwheel! Let's do that
